name: project_environment
dependencies:
  - python=3.6.2
  - numpy=1.17.3
  - pip:
      - azureml-defaults>=1.0.45
      - inference-schema[numpy-support]
      - gensim==3.8.3
      - nltk==3.5
      - pymorphy2==0.8
      - tensorflow==2.2.0